# Generated by Django 4.1.3 on 2022-11-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iou', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IouUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='ledger',
            name='owes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owed', to='iou.iouuser'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owes', to='iou.iouuser'),
        ),
    ]
