# Generated by Django 4.1.3 on 2022-11-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iou', '0002_iouuser_alter_ledger_owes_alter_ledger_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iouuser',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='iouuser',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
